### ISSUE TITLE
error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mob-sakai** [game-ci/unity-request-activation-file#53]
```
2020-11-17T04:26:08.8493398Z Retrieving manual activation file for unity version "2018.4.15f1".
2020-11-17T04:26:09.2851591Z /opt/unity/Editor/Unity: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
```

[Full log](https://github.com/webbertakken/unity-request-activation-file/files/5551261/2_Request.manual.activation.file.txt)

**Comment by webbertakken** [comment]
Will be solved when the next docker image is released (soon). The action's alpha version will automatically switch to the improved image

**Comment by mob-sakai** [comment]
Thanks for the quick response!

**Comment by webbertakken** [comment]
New version is merged. The new images will be building in the coming 24 hours. You can follow the progress on [Discord](http://unity-ci.com/discord) in the `#news` channel.

Closing this for now. Let me know if the problem persists.
