### ISSUE TITLE
Incorrect unity version

### ISSUE THREAD

**Issue by LuisMayo** [game-ci/unity-request-activation-file#71]
**Bug description**

It is generating a License for a different version that the one currently in use

**How to reproduce**

1. Have a repository with a unity project
2. In the folder ProjectSettings/ProjectVersion.txt have the following content:
```
m_EditorVersion: 2020.3.13f1
m_EditorVersionWithRevision: 2020.3.13f1 (71691879b7f5)
```
3. When running the request activation file, the following file is returned: `Unity_v2019.2.11f1.alf`
-

**Expected behavior**

It should return a file for the 2020 version of unity.

**Additional details**
The builder part of your project is also having trouble finding the ProjectVersion.txt, as well as the .git

Maybe my folder structure is not ok? Here it is. 

![image](https://user-images.githubusercontent.com/20229636/124741728-4e42a180-df1c-11eb-8354-55542f626bbb.png)

**Comment by webbertakken** [comment]
While that is semantically true, it will actually work across all versions as we hardcoded the machine id for CI in our docker images.

**Comment by 572005238** [comment]
I met same question, and I resolved it. [https://github.com/3-Delta/Unity-DeviceSafeArea/blob/main/.github/workflows/AcquireUnityActivationFile.yml](url)

**Comment by webbertakken** [comment]
Please just refer to the official docs instead. It works exactly the same way.

https://game.ci/docs
