### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Josephksa** [game-ci/unity-request-activation-file#78]
**Context**

Running the action on a windows machine seems not supported.
Not sure how to proceed if we want to build windows version using Personal License.

**Comment by GabLeRoux** [comment]
Licenses are not tied to unity versions or target platforms (windows, webgl, linux, macos, etc.). All you need is a valid license in your environment variables. Please follow instructions here:  
https://game.ci/docs/github/activation

It is possible to build for windows using a linux host using the unity builder action too. The only limitations are you won't be able to build for targets such as Universal Windows Platform (UWP) as this requires a windows host and we don't support that yet (We haven't built windows based docker images yet).

I'm closing this, but feel free to ask other questions if you get stuck somewhere.
